services:
  reservation:
    build:
      context: .
      dockerfile: ./apps/reservation/Dockerfile
      target: development
    command: npm run start:dev reservation
    env_file:
      - ./apps/reservation/.env
    ports:
      - '3000:3030'
    environment:
      - MONGO_URI=${MONGO_URI}
    volumes:
      - .:/usr/src/app

  auth:
    build:
      context: .
      dockerfile: ./apps/auth/Dockerfile
      target: development
    command: npm run start:dev auth
    env_file:
      - ./apps/auth/.env
    ports:
      - '3001:3031'
    environment:
      - MONGO_URI=${MONGO_URI}
    volumes:
      - .:/usr/src/app      
