services:
  reservation:
    build:
      context: .
      dockerfile: ./apps/reservation/Dockerfile
      target: development
    command: npm run start:dev reservation
    env_file:
      - ./.env
    ports:
      - '3000:3030'
    environment:
      - MONGO_URI=${MONGO_URI}
    volumes:
      - .:/usr/src/app
